name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch; adjust as needed for your workflow
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Checks out your repository

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates a GITHUB_TOKEN secret to use in workflows

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/azure-chat:latest  # Replace with your GHCR path and image name

      - name: Output image digest
        run: echo "The new image digest is ${{ steps.buildx.outputs.digest }}"